name: Contract Testing Pipeline

on:
  push:

  pull_request:

jobs:
  jest:
    name: Jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup dependencies
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: 'yarn'
          cache-dependency-path: './yarn.lock'
      - name: Install Git
        run: sudo apt install git -y
      - name: Install modules
        run: yarn install
      - name: Compile contracts for tests
        run: yarn compile
      - name: Start sandbox and wait for initialization
        run: yarn start-sandbox && sleep 10s
      - name: Test the contracts
        run: yarn test
      - name: Stop sandbox
        run: yarn stop-sandbox